# Generated by Django 6.0.1 on 2026-02-21 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='discounts_ends_at_after_starts_at'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('min_margin_b2b__gte', 0)), name='discounts_min_margin_b2b_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('min_margin_b2c__gte', 0)), name='discounts_min_margin_b2c_non_negative'),
        ),
    ]
